main: club.hardcoreminecraft.javase.RAD.main
name: AsyncRules
description: Rules Are Dumb! Never waste server resources fetching them.
author: JavaSE
version: 1.0.0
loadbefore: [Essentials]
commands:
  rules:
    description: See the servers rules. No permission required
  erules:
    description: See the servers rules. No permission required
permissions:
  JavaSE.rules.reload:
    default: op